### PR TITLE
Allow systemd.service settings to be overidden

### LINKED ISSUE #15: Need configurable basedir
https://github.com/nla/jvmctl/blob/master/jvmctl/jvmctl/jvmctl.py#L427

In this particular instance I need it for running Solr as a command line application because is scans the working directory for contexts.

Looks like something like this in the the conf file would be basic to add:
WORKING_DIR=/some/random/path

### PR DESCRIPTION
**Pull request by ato**
For example you could set a custom working dir by appending the
following to your jvmctl conf:

```
[systemd.service.Service]
WorkingDirectory=/ssd/myapp/data
```

Fixes #15

### CODE REVIEW

**Comment by ato** [comment]
@greg-pendlebury this do? You could in fact then use the same mechanism to replace ExecStart and even use to jvmctl deploy and run something that's not java. For example:

```
[systemd.service.Service]
WorkingDirectory=/apps/myapp
ExecStart=/usr/bin/python not_java.py
```

**Comment by greg-pendlebury** [comment]
Looks ok to me in terms of fixing my problem... is it a security problem though?

**Comment by ato** [comment]
Jvmctl has never tried to properly enforce security. Add USER=root and it'll run a jvm as root which can then do whatever you want.

Builds run as an unprivileged user not to stop developers doing things as root but to prevent accidents like someone sticking rm -rf / in a deny script. Also to dissuade people from unmaintainable practices like changing system-wide config in one app's deploy script.

**Comment by ato** [comment]
Released as jvmctl 0.4.0. `sudo yum clean metadata; sudo yum update jvmctl` to get it

**Comment by JonathanShaw** [comment]
the spacewalk repo only syncs once a day.  I just manually updated it so the centos machines should be able to grab it now

**Comment by ato** [comment]
Ah, thanks Jon.

**Pull request merged**
