### PR TITLE
Collect heap dump on out of memory error by default

### PR DESCRIPTION
**Pull request by ato**
We only keep the latest dump for each application to avoid filling
up the disk if the application OOMs multiple times.

Can be disabled on per-JVM or per-server option by clearing
HEAP_DUMP_OPTS in the app config or in /etc/jvmctl.conf
respectively.

### CODE REVIEW

**Comment by JonathanShaw** [comment]
so exposing HEAP_DUMP_OPTS is mostly for enabling/disabling right?  because if they change the path it writes to then the move function will fail. could we change it to an explicit boolean in the config? it doesn't look like there's any additional flags could be set.

Other than that it looks good to me.

**Comment by ato** [comment]
Good point. I was vaguely thinking there might be other options but that really doesn't make any sense and you could always add whatever you want to JAVA_OPTS anyway.

How about this. I've changed it so the option is HEAP_DUMP_PATH.

If you set it to a file it'll append .tmp to the filename when specifying on the Java command-line and the OOM script will rename the .tmp file replacing any previous dump. (We need to do this temp file and rename as the JVM will refuse to dump if the file exists and the default we're after is keeping just the most recent dump to avoid filling disk.)

If you set it to a directory it'll just pass the path through as is and the JVM will create multiple dump files.

If you blank it out it won't pass any heap dump options to the JVM.

**Comment by anniecollins-nla** [comment]
Looks good to me.
I wonder if we have enough default parameters now that they should be all populated in the default new config file prefixed with a comment (#). Like currently happens with REPO JAVA_OPTS and HEAP_SIZE

**Comment by ato** [comment]
Released as 0.5.0, package in the bss repo.

> I wonder if we have enough default parameters now that they should be all populated in the default new
> config file prefixed with a comment (#). Like currently happens with REPO JAVA_OPTS and HEAP_SIZE
Yeah. Do you want to give that a go?

I think they're all listed in the DEFAULTS at the top of jvmctl.py. They just needed to be added to the prints under `def new(node):`.

**Pull request merged**
